version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'health_and_wellness_services'
      POSTGRES_PASSWORD: 'Passw0rd!'
      POSTGRES_USER: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
    driver: local
